from __future__ import annotations

import os
import pathlib
import re

from PIL import Image, ImageDraw, ImageFont


ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
OUT = SRC / "display" / "cjkfont_gen.go"
FONT_CANDIDATES = [
    pathlib.Path(r"C:\Windows\Fonts\msyh.ttc"),
    pathlib.Path(r"C:\Windows\Fonts\simhei.ttf"),
    pathlib.Path(r"C:\Windows\Fonts\simsun.ttc"),
]
SIZE = 12

PUNCTUATION = "，。！？；：、“”‘’（）【】《》￥…—·"
COMMON_SYMBOLS = "✓✔✗✘×○●□■△▲▽▼★☆♥❤"


def gb2312_level1_chars() -> set[str]:
    chars: set[str] = set()
    for high in range(0xB0, 0xD8):
        for low in range(0xA1, 0xFF):
            try:
                chars.add(bytes([high, low]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return chars


def collect_chars() -> list[str]:
    chars = gb2312_level1_chars()
    chars.update(PUNCTUATION)
    chars.update(COMMON_SYMBOLS)
    for path in SRC.rglob("*"):
        if path.suffix not in {".go", ".html"}:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        chars.update(re.findall(r"[\u3400-\u9fff]", text))
    chars.update(re.findall(r"[\u3400-\u9fff]", os.environ.get("CJK_EXTRA_TEXT", "")))
    return sorted(ch for ch in chars if ord(ch) <= 0xFFFF)


def font_path() -> pathlib.Path:
    for candidate in FONT_CANDIDATES:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("no CJK font found; install Noto Sans CJK or edit FONT_CANDIDATES")


def glyph_rows(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    image = Image.new("L", (SIZE, SIZE), 0)
    draw = ImageDraw.Draw(image)
    bbox = font.getbbox(ch)
    width = bbox[2] - bbox[0]
    height = bbox[3] - bbox[1]
    x = (SIZE - width) // 2 - bbox[0]
    y = (SIZE - height) // 2 - bbox[1]
    draw.text((x, y), ch, font=font, fill=255)

    rows: list[int] = []
    pixels = image.load()
    for row in range(SIZE):
        bits = 0
        for col in range(SIZE):
            if pixels[col, row] >= 96:
                bits |= 1 << (SIZE - 1 - col)
        rows.append(bits)
    return rows


def go_bytes_literal(data: bytes, chunk_size: int = 48) -> list[str]:
    chunks: list[str] = []
    for i in range(0, len(data), chunk_size):
        chunk = data[i : i + chunk_size]
        chunks.append('"' + "".join(f"\\x{b:02x}" for b in chunk) + '"')
    return chunks


def append_const_blob(lines: list[str], name: str, data: bytes) -> None:
    lines.append(f"const {name} = \"\" +")
    chunks = go_bytes_literal(data)
    for i, chunk in enumerate(chunks):
        suffix = "" if i == len(chunks) - 1 else " +"
        lines.append(f"\t{chunk}{suffix}")
    lines.append("")


def main() -> None:
    chars = collect_chars()
    font = ImageFont.truetype(str(font_path()), SIZE)

    code_data = bytearray()
    glyph_data = bytearray()
    for ch in chars:
        code = ord(ch)
        code_data.extend([(code >> 8) & 0xFF, code & 0xFF])
        for row in glyph_rows(font, ch):
            glyph_data.extend([(row >> 16) & 0xFF, (row >> 8) & 0xFF, row & 0xFF])

    lines: list[str] = [
        "// Code generated by tools/fontsubset/generate_cjk.py; DO NOT EDIT.",
        "",
        "package display",
        "",
        "const (",
        f"\tcjkGlyphWidth  = int16({SIZE})",
        f"\tcjkGlyphHeight = int16({SIZE})",
        f"\tcjkGlyphCount  = {len(chars)}",
        "\tcjkCodeBytes   = 2",
        "\tcjkRowBytes    = 3",
        "\tcjkGlyphBytes  = int(cjkGlyphHeight) * cjkRowBytes",
        ")",
        "",
    ]
    append_const_blob(lines, "cjkGlyphCodes", bytes(code_data))
    append_const_blob(lines, "cjkGlyphData", bytes(glyph_data))
    lines.extend(
        [
            "func lookupCJKGlyph(r rune) (int, bool) {",
            "\tif r > 0xffff {",
            "\t\treturn 0, false",
            "\t}",
            "\ttarget := uint16(r)",
            "\tlow := 0",
            "\thigh := cjkGlyphCount - 1",
            "\tfor low <= high {",
            "\t\tmid := low + (high-low)/2",
            "\t\tcode := cjkGlyphCodeAt(mid)",
            "\t\tif code == target {",
            "\t\t\treturn mid, true",
            "\t\t}",
            "\t\tif code < target {",
            "\t\t\tlow = mid + 1",
            "\t\t} else {",
            "\t\t\thigh = mid - 1",
            "\t\t}",
            "\t}",
            "\treturn 0, false",
            "}",
            "",
            "func cjkGlyphCodeAt(index int) uint16 {",
            "\toff := index * cjkCodeBytes",
            "\treturn uint16(cjkGlyphCodes[off])<<8 | uint16(cjkGlyphCodes[off+1])",
            "}",
            "",
            "func cjkGlyphRow(index int, row int16) uint32 {",
            "\toff := index*cjkGlyphBytes + int(row)*cjkRowBytes",
            "\treturn uint32(cjkGlyphData[off])<<16 | uint32(cjkGlyphData[off+1])<<8 | uint32(cjkGlyphData[off+2])",
            "}",
            "",
        ]
    )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(chars)} glyphs at {SIZE}x{SIZE}")


if __name__ == "__main__":
    main()
